export const QUERY_KEY = {
  PLACE: {
    REGION: 'REGION',
    PLACE: 'PLACE',
    COURSE: 'COURSE',
    CAFE: 'CAFE',
    RESTAURANT: 'RESTAURANT',
    STAY: 'STAY',
    CITY_CODE: 'CITY_CODE',
    SEARCH_PLACE: 'SEARCH_PLACE',
    SEARCH_STAY: 'SEARCH_STAY',
  },
} as const;
