export const DB = {
  region: [
    {
      placeId: 1,
      name: '제주 해수욕장',
      description: '대충 설명 설명',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 2,
      name: '제주 해수욕장2',
      description: '대충 설명 설명',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 3,
      name: '제주 해수욕장3',
      description: '대충 설명 설명2',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 4,
      name: '제주 해수욕장4',
      description: '대충 설명 설명3',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 5,
      name: '제주 해수욕장5',
      description: '대충 설명 설명4',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 6,
      name: '제주 해수욕장6',
      description: '대충 설명 설명6',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 7,
      name: '제주 해수욕장7',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
  ],
  course: [
    {
      placeId: 1,
      name: '제주도 코스 입니다.',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 2,
      name: '제주도 코스 입니다.',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 3,
      name: '제주도 코스 입니다.',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 4,
      name: '제주도 코스 입니다.',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
    {
      placeId: 5,
      name: '제주도 코스 입니다.',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
  ],
  place: [
    {
      placeId: 1,
      name: '제주도 명소 입니다ㅏ.',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: '타입1',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 15,
      rating: 4.2,
    },
  ],
  cafe: [
    {
      placeId: 1,
      name: '제주도 카페 입니다.',
      description: '대충 설명 설명7',
      addr: '제주도 어딘가',
      type: 'cafe',
      latitude: 123123.123,
      longitude: 123123.123,
      likeCount: 5,
      imageURL: 'https://placehold.co/200x200',
      commentCount: 2,
      rating: 4.9,
    },
  ],
  cityCode: [
    {
      code: 1,
      name: '서울',
    },
    {
      code: 2,
      name: '부산',
    },
    {
      code: 3,
      name: '제주도',
    },
    {
      code: 4,
      name: '경북',
    },
    {
      code: 5,
      name: '경남',
    },
  ],
  searchPlace: [
    {
      id: 1,
      imageUrl: 'https://placehold.co/47x47',
      name: '제주 해수욕장',
      type: 'place',
      averageRating: '4.2',
      commentCount: 15,
      latitude: 33.5067,
      longitude: 126.493,
    },
    {
      id: 2,
      imageUrl: 'https://placehold.co/47x47',
      name: '제주 해수욕장2',
      type: 'place',
      averageRating: '4.2',
      commentCount: 12,
      latitude: 33.4587,
      longitude: 126.9426,
    },
    {
      id: 3,
      imageUrl: 'https://placehold.co/47x47',
      name: '용두암 카페',
      type: 'cafe',
      averageRating: '4.2',
      commentCount: 12,
      latitude: 33.5161,
      longitude: 126.5116,
    },
    {
      id: 4,
      imageUrl: 'https://placehold.co/47x47',
      name: '제주올레 음식',
      type: 'restaurant',
      averageRating: '4.2',
      commentCount: 14,
      latitude: 33.2367,
      longitude: 126.505,
    },
    {
      id: 5,
      imageUrl: 'https://placehold.co/47x47',
      name: '아쿠아플라넷 제주',
      type: 'place',
      averageRating: '4.2',
      commentCount: 19,
      latitude: 33.256,
      longitude: 126.4076,
    },
    {
      id: 6,
      imageUrl: 'https://placehold.co/47x47',
      name: '아쿠아플라넷 제주1',
      type: 'place',
      averageRating: '4.2',
      commentCount: 19,
      latitude: 33.256,
      longitude: 126.4076,
    },
    {
      id: 7,
      imageUrl: 'https://placehold.co/47x47',
      name: '아쿠아플라넷 제주2',
      type: 'place',
      averageRating: '4.2',
      commentCount: 19,
      latitude: 33.256,
      longitude: 126.4076,
    },
    {
      id: 8,
      imageUrl: 'https://placehold.co/47x47',
      name: '아쿠아플라넷 3',
      type: 'place',
      averageRating: '4.9',
      commentCount: 19,
      latitude: 33.256,
      longitude: 126.4076,
    },
  ],
  searchStay: [
    {
      id: 1,
      imageUrl: 'https://placehold.co/47x47',
      name: '제주 리조트',
      type: 'stay',
      averageRating: '4.2',
      commentCount: 15,
      latitude: 33.489,
      longitude: 126.498,
    },
    {
      id: 2,
      imageUrl: 'https://placehold.co/47x47',
      name: '성산 펜션',
      type: 'stay',
      averageRating: '4.2',
      commentCount: 15,
      latitude: 33.4587,
      longitude: 126.9426,
    },
    {
      id: 3,
      imageUrl: 'https://placehold.co/47x47',
      name: '애월 민박',
      type: 'stay',
      averageRating: '4.2',
      commentCount: 15,
      latitude: 33.4639,
      longitude: 126.3111,
    },
  ],
};
